import * as z from "zod";

export const SendgridEventSchema = z.object({
  email: z.string(),
  timestamp: z.number(),
  event: z.enum(["open", "click"]),
  // sent with click events, the  URL that was clicked
  url: z.string().optional(),
  /**
   * Indicates whether or not an open event has been generated by Apple Mail Privacy Protection (MPP).
   * When this field is set to true, it means that SendGrid has received signals indicating that a recipient with MPP enabled has triggered an open event.
   * When this field is false, it indicates that the event was triggered by a conventional open.
   */
  sg_machine_open: z.boolean().optional(),
  category: z.string().array().optional(),
  sg_event_id: z.string(),
  sg_message_id: z.string(),
  marketing_campaign_id: z.string().optional(),
  marketing_campaign_name: z.string().optional(),
  mc_auto_id: z.string().optional(),
  mc_auto_name: z.string().optional(),
  useragent: z.string(),
  ip: z.string(),
});

export type SendgridEvent = z.infer<typeof SendgridEventSchema>;
export const SendgridEventsSchema = z.array(SendgridEventSchema);
